# 员工服务配置文件 - 实例3
server:
  port: 8085
  servlet:
    context-path: /

spring:
  application:
    name: employee-service-instance3
  
  # MySQL数据库配置 - 稳定连接配置
  datasource:
    url: jdbc:mysql://172.29.179.55:3306/employees?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: x1zhimen
    
    # HikariCP连接池配置 - 实例3优化
    hikari:
      minimum-idle: 3                    # 最小空闲连接数
      maximum-pool-size: 10              # 最大连接池大小
      idle-timeout: 600000               # 空闲连接超时时间(10分钟)
      pool-name: EmployeeHikariPool-3
      max-lifetime: 1800000              # 连接最大生命周期(30分钟)
      connection-timeout: 10000          # 连接超时时间(10秒)
      validation-timeout: 5000           # 验证超时时间(5秒)
      leak-detection-threshold: 60000    # 连接泄露检测阈值(60秒)
      connection-test-query: SELECT 1    # 连接测试查询
      connection-init-sql: SELECT 1      # 连接初始化SQL
      keepalive-time: 30000              # 保活时间(30秒)
      register-mbeans: true              # 注册MBean用于监控
      auto-commit: false                 # 关键设置：禁用自动提交
    
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none  # 不自动创建表，使用现有的employees数据库
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false  # 关闭SQL日志以提高性能
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20                 # 批处理大小
          fetch_size: 50                 # 获取大小
        connection:
          provider_disables_autocommit: true  # 禁用自动提交优化
          autocommit: false              # 明确禁用自动提交
        order_inserts: true              # 优化插入顺序
        order_updates: true              # 优化更新顺序
        batch_versioned_data: true       # 批处理版本化数据
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        
  # Jackson配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false

# 日志配置 - 实例3
logging:
  level:
    com.userservice: INFO              # 业务日志级别
    org.springframework.web: WARN      # 减少Spring Web日志
    org.hibernate.SQL: WARN            # 减少SQL日志
    org.hibernate.type: WARN           # 减少类型日志
    com.zaxxer.hikari: INFO            # HikariCP日志
    org.springframework.boot: INFO     # Spring Boot日志
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [实例3] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [实例3] %msg%n"
  file:
    name: logs/employee-service-instance3.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env
  endpoint:
    health:
      show-details: when-authorized
    env:
      show-values: when-authorized 