# 快速启动配置 - 用于开发环境
spring:
  datasource:
    url: jdbc:mysql://172.29.179.55:3306/employees?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=5000&socketTimeout=10000&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: x1zhimen
    
    # 快速启动连接池配置
    hikari:
      minimum-idle: 2                    # 最小连接数
      maximum-pool-size: 8               # 适中的连接池大小
      connection-timeout: 8000           # 连接超时8秒
      validation-timeout: 3000           # 验证超时3秒
      initialization-fail-timeout: 10000 # 初始化失败超时10秒
      connection-test-query: SELECT 1
      keepalive-time: 60000              # 保活时间1分钟
      auto-commit: false                 # 禁用自动提交
      
  # JPA快速启动配置
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
        connection:
          provider_disables_autocommit: true
          autocommit: false              # 明确禁用自动提交
        temp:
          use_jdbc_metadata_defaults: false  # 禁用JDBC元数据默认值

# 开发环境日志配置
logging:
  level:
    root: WARN
    com.userservice: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: INFO             # 显示连接池信息
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{0} - %msg%n" 